import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10 },
  header: { marginBottom: 20, textAlign: "center", fontSize: 16, fontWeight: "bold" },
  row: { flexDirection: "row", marginBottom: 5 },
  label: { width: "30%", fontWeight: "bold" },
  value: { width: "70%" },
  section: { marginTop: 20, marginBottom: 10, fontWeight: "bold" },
  text: { marginBottom: 5 },
});

export default function BillOfLadingPDF({ shipment, buyer }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>BILL OF LADING INSTRUCTION</Text>

        <View style={styles.row}>
          <Text style={styles.label}>Shipper:</Text>
          <Text style={styles.value}>Your Company Name\nYour Company Address</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Consignee:</Text>
          <Text style={styles.value}>{buyer.companyName}\n{buyer.address}\n{buyer.city}, {buyer.country}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Notify Party:</Text>
          <Text style={styles.value}>Same as consignee</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Vessel / Flight:</Text>
          <Text style={styles.value}>{shipment.vesselName || "To be advised"}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Port of Loading:</Text>
          <Text style={styles.value}>{shipment.portOfLoading || "N/A"}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Port of Discharge:</Text>
          <Text style={styles.value}>{shipment.portOfDischarge || "N/A"}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Container / Seal No.:</Text>
          <Text style={styles.value}>{shipment.containerNumber || "To be advised"}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Marks & Numbers:</Text>
          <Text style={styles.value}>{shipment.shippingMarks || "N/A"}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Number of Packages:</Text>
          <Text style={styles.value}>{shipment.totalCtn || "N/A"}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Gross Weight (KG):</Text>
          <Text style={styles.value}>{shipment.totalGrossWeight || "N/A"}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Measurement (CBM):</Text>
          <Text style={styles.value}>{shipment.totalVolume || "N/A"}</Text>
        </View>

        <Text style={styles.section}>Special Instructions:</Text>
        <Text style={styles.text}>- Bill of Lading to be issued "Shipped on Board"</Text>
        <Text style={styles.text}>- 3 originals and 3 copies required</Text>
        <Text style={styles.text}>- Please advise B/L number and ETD promptly</Text>
        <Text style={styles.text}>- Telex release allowed</Text>

        <Text style={{ marginTop: 40, fontSize: 8, textAlign: "center" }}>
          Generated by ExportDocs – {new Date().toLocaleString()}
        </Text>
      </Page>
    </Document>
  );
}