import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10 },
  header: { marginBottom: 20, textAlign: "center", fontSize: 16, fontWeight: "bold" },
  row: { flexDirection: "row", marginBottom: 5 },
  label: { width: "30%", fontWeight: "bold" },
  value: { width: "70%" },
  table: { marginTop: 20, borderWidth: 1, borderColor: "#000" },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#000" },
  tableHeader: { fontWeight: "bold", backgroundColor: "#f0f0f0" },
  tableCol: { flex: 1, padding: 5 },
  signature: { marginTop: 40, flexDirection: "row", justifyContent: "space-between" },
});

export default function CertificateOfOriginPDF({ shipment, buyer, user }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>CERTIFICATE OF ORIGIN</Text>
        <Text style={{ textAlign: "center", marginBottom: 20 }}>(GSP Form A – For EU)</Text>

        <View style={styles.row}>
          <Text style={styles.label}>Exporter:</Text>
          <Text style={styles.value}>{user.companyName || "Your Company Name"}\n{user.companyAddress || ""}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Consignee:</Text>
          <Text style={styles.value}>{buyer.companyName}\n{buyer.address}\n{buyer.city}, {buyer.country}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Invoice No.:</Text>
          <Text style={styles.value}>{shipment.shipmentNumber}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Country of Origin:</Text>
          <Text style={styles.value}>Pakistan</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Country of Destination:</Text>
          <Text style={styles.value}>{buyer.country}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Port of Loading:</Text>
          <Text style={styles.value}>{shipment.portOfLoading || "N/A"}</Text>
        </View>

        <Text style={{ marginTop: 20, fontWeight: "bold" }}>Declaration by Exporter:</Text>
        <Text style={{ marginTop: 10 }}>
          The undersigned hereby declares that the above goods originate in Pakistan and that the information given is correct.
        </Text>

        <View style={styles.signature}>
          <Text>Place and date: _______________</Text>
          <Text>Signature: _______________</Text>
        </View>

        <Text style={{ marginTop: 40, fontSize: 8, textAlign: "center" }}>
          Generated by ExportDocs – {new Date().toLocaleString()}
        </Text>
      </Page>
    </Document>
  );
}