import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10 },
  header: { marginBottom: 20, textAlign: "center", fontSize: 16, fontWeight: "bold" },
  row: { flexDirection: "row", marginBottom: 5 },
  label: { width: "30%", fontWeight: "bold" },
  value: { width: "70%" },
  table: { marginTop: 20, borderWidth: 1, borderColor: "#000" },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#000" },
  tableHeader: { fontWeight: "bold", backgroundColor: "#f0f0f0" },
  tableCol: { flex: 1, padding: 5 },
  total: { marginTop: 20, textAlign: "right", fontWeight: "bold" },
});

export default function ProformaInvoicePDF({ shipment, buyer, user, items }) {
  const invoiceDate = new Date(shipment.shipmentDate).toLocaleDateString();

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>PROFORMA INVOICE</Text>
        <Text style={{ textAlign: "center", marginBottom: 20, fontSize: 9 }}>(Not a commercial invoice – for advance payment / LC purposes)</Text>

        <View style={styles.row}>
          <Text style={styles.label}>Seller:</Text>
          <Text style={styles.value}>{user.companyName || "Your Company Name"}\n{user.companyAddress || ""}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Buyer:</Text>
          <Text style={styles.value}>{buyer.companyName}\n{buyer.address}\n{buyer.city}, {buyer.country}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Proforma Invoice #:</Text>
          <Text style={styles.value}>{shipment.shipmentNumber}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Date:</Text>
          <Text style={styles.value}>{invoiceDate}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>LC #:</Text>
          <Text style={styles.value}>{shipment.lcNumber || "N/A"}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Incoterm:</Text>
          <Text style={styles.value}>{shipment.incoterm}</Text>
        </View>

        <View style={styles.table}>
          <View style={[styles.tableRow, styles.tableHeader]}>
            <Text style={styles.tableCol}>Description</Text>
            <Text style={styles.tableCol}>Quantity</Text>
            <Text style={styles.tableCol}>Unit Price (USD)</Text>
            <Text style={styles.tableCol}>Total (USD)</Text>
          </View>
          {items.map((item, idx) => (
            <View key={idx} style={styles.tableRow}>
              <Text style={styles.tableCol}>{item.description}</Text>
              <Text style={styles.tableCol}>{item.quantity}</Text>
              <Text style={styles.tableCol}>{item.unitPrice.toFixed(2)}</Text>
              <Text style={styles.tableCol}>{(item.quantity * item.unitPrice).toFixed(2)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.total}>
          <Text>Subtotal: ${shipment.subtotal.toFixed(2)}</Text>
          <Text>Discount: ${shipment.discount.toFixed(2)}</Text>
          <Text>Shipping: ${shipment.shippingCharge.toFixed(2)}</Text>
          <Text style={{ fontSize: 12, marginTop: 5 }}>Total Amount: ${shipment.totalAmount.toFixed(2)}</Text>
        </View>

        <Text style={{ marginTop: 40, fontSize: 8, textAlign: "center" }}>
          This is a proforma invoice – valid for advance payment only. Commercial invoice will follow.
        </Text>
        <Text style={{ marginTop: 5, fontSize: 8, textAlign: "center" }}>
          Generated by ExportDocs – {new Date().toLocaleString()}
        </Text>
      </Page>
    </Document>
  );
}